# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

    paths:
      - 'test/washing_machine_questions.csv'
      - 'test_mode.py'
      - 'core/wash_fsm/text_washer_assistant.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS files manually
        run: |
          git lfs install
          git lfs pull
          
      - name: Extract Archive
        run: |
          echo -e "\n\n[$(date '+%Y-%m-%d %H:%M:%S')] [>>>>>>>>>>] Starting the test mode [>>>>>>>>>>]\n" >> ~/status.txt
          # Verify file existence and size
          ls -lh .venv.tar.gz || echo "File not found"
          echo -e "\n[$(date '+%Y-%m-%d %H:%M:%S')] Extracting environment...\n" >> ~/status.txt
          tar -xzf .venv.tar.gz || { echo "Tar failed"; exit 1; }
                    
      - name: Run Application
        run: |
          source .venv/bin/activate
          python test_mode.py | tee -a ~/status.txt
          echo -e "\n[$(date '+%Y-%m-%d %H:%M:%S')] [<<<<<<<<<<] Execution completed! [<<<<<<<<<<]\n" >> ~/status.txt

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: check file existance
        run: |
          if [ -z "$HOME" ]; then
            echo -e "Error: \$HOME variable is not set."
          elif [ -f "$HOME/status.txt" ]; then
            echo -e "Confirmed: status.txt exists in $HOME"
          else
            echo -e "File not found: status.txt is missing from $HOME"
          fi
      
